GET http://localhost:5120/games

###
GET http://localhost:5120/games/3

###
POST http://localhost:5120/games
Content-Type: application/json

{
    "name": "Fortnite",
    "genreId": 2,
    "price": 25.99,
    "releaseDate": "2016-10-20"
}

###
PUT http://localhost:5120/games/3
Content-Type: application/json

 {
    "name": "Fortnite Battle Royale",
    "genreId": 2,
    "price": 15.99,
    "releaseDate": "2016-08-19"
 }

###
DELETE http://localhost:5120/games/2